this.mailParserTests = {

    "Create mailParser instance, load test file": function(test){
        loadParserTestFile("M1", function(err, data){
            test.ifError(err);
            test.ok(data);
            
            var mc = mailParser();
            test.ok(true, mc instanceof mailParser);
            test.done();
        });
    },

    "M1": function(test){
        loadParserTestFile("M1", function(err, data){
            test.ifError(err);
            test.ok(data);

            var mc = mailParser();
            mc.write(new TextDecoder("utf-8").decode(data));
            mc.end();
            
            var tree = mc.getParsedTree();

            test.deepEqual( tree.headers, {subject:"M1", 'mime-version':"1.0 (Generated by hand by paf@swip.net)", to:"(requester of the test)", from:"mimetest-human@imc.org"});
            test.equal(tree.body, "  M1\n    Always generate a \"MIME-Version: 1.0\" header field.\n\n\n");

            test.done();
        });
    },

    "M1-1": function(test){
        loadParserTestFile("M1-1", function(err, data){
            test.ifError(err);
            test.ok(data);

            var mc = mailParser();
            mc.write(new TextDecoder("utf-8").decode(data));
            mc.end();
            
            var tree = mc.getParsedTree();

            test.deepEqual( tree.headers, {"subject":"M1-1","mime-version":"1.0","to":"(requester of the test)","from":"mimetest-human@imc.org"});
            test.equal(tree.body, "  M1\n    Always generate a \"MIME-Version: 1.0\" header field.\n\n\n");

            test.done();
        });
    },

    "M1-2": function(test){
        loadParserTestFile("M1-2", function(err, data){
            test.ifError(err);
            test.ok(data);

            var mc = mailParser();
            mc.write(new TextDecoder("utf-8").decode(data));
            mc.end();
            
            var tree = mc.getParsedTree();

            test.deepEqual( tree.headers, {"subject":"M1-2","mime-version":"2.0 (Generated by hand by paf@swip.net)","to":"(requester of the test)","from":"mimetest-human@imc.org"});
            test.equal(tree.body, "  M1\n    Always generate a \"MIME-Version: 1.0\" header field.\n\n    Note that the MIME-version for this message is 2.0.\n\n");

            test.done();
        });
    }

}